# Generated by Django 4.1.5 on 2023-01-19 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_city', models.CharField(max_length=100)),
                ('req_temp', models.CharField(max_length=100)),
                ('req_weather', models.CharField(max_length=100)),
            ],
        ),
    ]
